# docker-compose.yml
version: '3'
services:
    prometheus:
        container_name: prometheus
        # If running on a 32-bit Raspberry Pi, use:
        # image: prom/prometheus:v1.7.2
        build: ./prometheus
        volumes:
            - prometheus_data:/prometheus
        command:
            - '--config.file=/etc/prometheus/prometheus.yml'
            - '--web.console.libraries=/etc/prometheus/console_libraries'
            - '--web.console.templates=/etc/prometheus/consoles'
            - '--storage.tsdb.retention.time=3m'
            - '--web.enable-lifecycle'
        ports:
            - "8090:9090"
        restart: on-failure
    node-exporter:
        container_name: node-exporter
        image: prom/node-exporter-linux-armv7
        ports:
            - "8092:9100"
        restart: on-failure
    grafana:
        container_name: grafana
        image: grafana/grafana:latest
        environment:
            - GF_SECURITY_ADMIN_PASSWORD=password
            - GF_AUTH_ANONYMOUS_ENABLED=true
            - GF_AUTH_DISABLE_LOGIN_FORM=false
            - GF_ORG_NAME=Main Org.
            - GF_ORG_ROLE=viewer
        volumes:
            - grafana_data:/var/lib/grafana
        depends_on:
            - prometheus
        ports:
            - "8091:3000"
        restart: on-failure
    alertmanager:
        container_name: alertmanager
        build: ./alertmanager
        command:
            - '--config.file=/alertmanager.yml'
        ports:
            - "8093:9093"
        restart: on-failure

volumes:
    prometheus_data: {}
    grafana_data: {}
    dhparam_cache: {}
