# prometheus.yml
global:
  scrape_interval: 5s
  external_labels:
    monitor: 'my-monitor'
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:8090']
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:8092']
alerting:
  alertmanagers:
    - scheme: http
      static_configs:
      - targets: ['alertmanager:8093']
#rule_files:
#  - 'alert.rules'
